/**
 * 에러코드 상수 정의
 * 
 * 에러코드 구조: [DOMAIN]_[CATEGORY]_[SPECIFIC_ERROR]
 * 
 * DOMAIN:
 * - AUTH: 인증/인가 관련
 * - USER: 사용자 관리 관련
 * - PERMISSION: 권한 관리 관련
 * - WALLET: 지갑/거래 관련
 * - CUSTOMER: 고객 지원 관련
 * - SYSTEM: 시스템 관련
 * - VALIDATION: 입력 검증 관련
 * - NETWORK: 네트워크 관련
 * 
 * CATEGORY:
 * - AUTH: 인증
 * - AUTHZ: 인가/권한
 * - NOT_FOUND: 리소스 없음
 * - CONFLICT: 충돌
 * - INVALID: 유효하지 않음
 * - EXPIRED: 만료
 * - LOCKED: 잠김
 * - RATE_LIMIT: 요청 제한
 * - MAINTENANCE: 유지보수
 * - INTERNAL: 내부 오류
 */

export const ERROR_CODES = {
  // ===== 인증/인가 관련 에러 =====
  AUTH: {
    // 인증 에러
    AUTH_INVALID_CREDENTIALS: 'AUTH_AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_MISSING: 'AUTH_AUTH_TOKEN_MISSING',
    AUTH_TOKEN_INVALID: 'AUTH_AUTH_TOKEN_INVALID',
    AUTH_TOKEN_EXPIRED: 'AUTH_AUTH_TOKEN_EXPIRED',
    AUTH_REFRESH_TOKEN_INVALID: 'AUTH_AUTH_REFRESH_TOKEN_INVALID',
    AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_AUTH_REFRESH_TOKEN_EXPIRED',
    AUTH_ACCOUNT_PENDING: 'AUTH_AUTH_ACCOUNT_PENDING',
    AUTH_ACCOUNT_DEACTIVATED: 'AUTH_AUTH_ACCOUNT_DEACTIVATED',
    AUTH_ACCOUNT_LOCKED: 'AUTH_AUTH_ACCOUNT_LOCKED',
    AUTH_ACCOUNT_SUSPENDED: 'AUTH_AUTH_ACCOUNT_SUSPENDED',
    AUTH_ACCOUNT_NOT_FOUND: 'AUTH_AUTH_ACCOUNT_NOT_FOUND',
    AUTH_PASSWORD_INCORRECT: 'AUTH_AUTH_PASSWORD_INCORRECT',
    AUTH_SESSION_EXPIRED: 'AUTH_AUTH_SESSION_EXPIRED',
    AUTH_LOGOUT_FAILED: 'AUTH_AUTH_LOGOUT_FAILED',
    
    // 인가 에러
    AUTHZ_INSUFFICIENT_PERMISSIONS: 'AUTH_AUTHZ_INSUFFICIENT_PERMISSIONS',
    AUTHZ_ROLE_REQUIRED: 'AUTH_AUTHZ_ROLE_REQUIRED',
    AUTHZ_PERMISSION_DENIED: 'AUTH_AUTHZ_PERMISSION_DENIED',
    AUTHZ_MENU_ACCESS_DENIED: 'AUTH_AUTHZ_MENU_ACCESS_DENIED',
    AUTHZ_RESOURCE_ACCESS_DENIED: 'AUTH_AUTHZ_RESOURCE_ACCESS_DENIED',
    AUTHZ_OPERATION_NOT_ALLOWED: 'AUTH_AUTHZ_OPERATION_NOT_ALLOWED',
  },

  // ===== 사용자 관리 관련 에러 =====
  USER: {
    // 사용자 조회 에러
    USER_NOT_FOUND: 'USER_NOT_FOUND_USER_NOT_FOUND',
    USER_INACTIVE: 'USER_NOT_FOUND_USER_INACTIVE',
    USER_ALREADY_EXISTS: 'USER_CONFLICT_USER_ALREADY_EXISTS',
    USER_EMAIL_DUPLICATE: 'USER_CONFLICT_USER_EMAIL_DUPLICATE',
    USER_USERNAME_DUPLICATE: 'USER_CONFLICT_USER_USERNAME_DUPLICATE',
    
    // 사용자 상태 에러
    USER_ALREADY_APPROVED: 'USER_CONFLICT_USER_ALREADY_APPROVED',
    USER_ALREADY_REJECTED: 'USER_CONFLICT_USER_ALREADY_REJECTED',
    USER_ALREADY_SUSPENDED: 'USER_CONFLICT_USER_ALREADY_SUSPENDED',
    USER_ALREADY_ACTIVE: 'USER_CONFLICT_USER_ALREADY_ACTIVE',
    USER_ALREADY_INACTIVE: 'USER_CONFLICT_USER_ALREADY_INACTIVE',
    
    // 사용자 생성/수정 에러
    USER_CREATE_FAILED: 'USER_INVALID_USER_CREATE_FAILED',
    USER_UPDATE_FAILED: 'USER_INVALID_USER_UPDATE_FAILED',
    USER_DELETE_FAILED: 'USER_INVALID_USER_DELETE_FAILED',
    USER_PASSWORD_RESET_FAILED: 'USER_INVALID_USER_PASSWORD_RESET_FAILED',
    USER_PROFILE_UPDATE_FAILED: 'USER_INVALID_USER_PROFILE_UPDATE_FAILED',
    
    // 사용자 승인/거부 에러
    USER_APPROVAL_FAILED: 'USER_INVALID_USER_APPROVAL_FAILED',
    USER_REJECTION_FAILED: 'USER_INVALID_USER_REJECTION_FAILED',
    USER_SUSPENSION_FAILED: 'USER_INVALID_USER_SUSPENSION_FAILED',
    USER_ACTIVATION_FAILED: 'USER_INVALID_USER_ACTIVATION_FAILED',
    
    // 대량 작업 에러
    USER_BULK_ACTION_FAILED: 'USER_INVALID_USER_BULK_ACTION_FAILED',
    USER_BULK_UPDATE_FAILED: 'USER_INVALID_USER_BULK_UPDATE_FAILED',
    USER_BULK_DELETE_FAILED: 'USER_INVALID_USER_BULK_DELETE_FAILED',
  },

  // ===== 권한 관리 관련 에러 =====
  PERMISSION: {
    // 권한 조회 에러
    PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND_PERMISSION_NOT_FOUND',
    PERMISSION_DENIED: 'PERMISSION_AUTHZ_PERMISSION_DENIED',
    PERMISSION_INSUFFICIENT: 'PERMISSION_AUTHZ_PERMISSION_INSUFFICIENT',
    
    // 역할 관리 에러
    ROLE_NOT_FOUND: 'PERMISSION_NOT_FOUND_ROLE_NOT_FOUND',
    ROLE_ALREADY_EXISTS: 'PERMISSION_CONFLICT_ROLE_ALREADY_EXISTS',
    ROLE_CREATE_FAILED: 'PERMISSION_INVALID_ROLE_CREATE_FAILED',
    ROLE_UPDATE_FAILED: 'PERMISSION_INVALID_ROLE_UPDATE_FAILED',
    ROLE_DELETE_FAILED: 'PERMISSION_INVALID_ROLE_DELETE_FAILED',
    ROLE_ASSIGN_FAILED: 'PERMISSION_INVALID_ROLE_ASSIGN_FAILED',
    ROLE_REVOKE_FAILED: 'PERMISSION_INVALID_ROLE_REVOKE_FAILED',
    
    // 권한 할당 에러
    PERMISSION_ASSIGN_FAILED: 'PERMISSION_INVALID_PERMISSION_ASSIGN_FAILED',
    PERMISSION_REVOKE_FAILED: 'PERMISSION_INVALID_PERMISSION_REVOKE_FAILED',
    PERMISSION_GRANT_FAILED: 'PERMISSION_INVALID_PERMISSION_GRANT_FAILED',
    PERMISSION_DENY_FAILED: 'PERMISSION_INVALID_PERMISSION_DENY_FAILED',
    
    // 권한 검증 에러
    PERMISSION_VALIDATION_FAILED: 'PERMISSION_INVALID_PERMISSION_VALIDATION_FAILED',
    PERMISSION_CHECK_FAILED: 'PERMISSION_INVALID_PERMISSION_CHECK_FAILED',
    PERMISSION_VERIFY_FAILED: 'PERMISSION_INVALID_PERMISSION_VERIFY_FAILED',
  },

  // ===== 지갑/거래 관련 에러 =====
  WALLET: {
    // 지갑 조회 에러
    WALLET_NOT_FOUND: 'WALLET_NOT_FOUND_WALLET_NOT_FOUND',
    WALLET_INACTIVE: 'WALLET_NOT_FOUND_WALLET_INACTIVE',
    WALLET_SUSPENDED: 'WALLET_NOT_FOUND_WALLET_SUSPENDED',
    
    // 거래 에러
    TRANSACTION_NOT_FOUND: 'WALLET_NOT_FOUND_TRANSACTION_NOT_FOUND',
    TRANSACTION_INVALID: 'WALLET_INVALID_TRANSACTION_INVALID',
    TRANSACTION_FAILED: 'WALLET_INVALID_TRANSACTION_FAILED',
    TRANSACTION_PENDING: 'WALLET_CONFLICT_TRANSACTION_PENDING',
    TRANSACTION_COMPLETED: 'WALLET_CONFLICT_TRANSACTION_COMPLETED',
    TRANSACTION_CANCELLED: 'WALLET_CONFLICT_TRANSACTION_CANCELLED',
    
    // 잔액 에러
    INSUFFICIENT_BALANCE: 'WALLET_INVALID_INSUFFICIENT_BALANCE',
    BALANCE_LOCKED: 'WALLET_LOCKED_BALANCE_LOCKED',
    BALANCE_FROZEN: 'WALLET_LOCKED_BALANCE_FROZEN',
    
    // 입출금 에러
    DEPOSIT_FAILED: 'WALLET_INVALID_DEPOSIT_FAILED',
    WITHDRAWAL_FAILED: 'WALLET_INVALID_WITHDRAWAL_FAILED',
    TRANSFER_FAILED: 'WALLET_INVALID_TRANSFER_FAILED',
    EXCHANGE_FAILED: 'WALLET_INVALID_EXCHANGE_FAILED',
  },

  // ===== 고객 지원 관련 에러 =====
  CUSTOMER: {
    // 문의 조회 에러
    INQUIRY_NOT_FOUND: 'CUSTOMER_NOT_FOUND_INQUIRY_NOT_FOUND',
    TICKET_NOT_FOUND: 'CUSTOMER_NOT_FOUND_TICKET_NOT_FOUND',
    SUPPORT_NOT_FOUND: 'CUSTOMER_NOT_FOUND_SUPPORT_NOT_FOUND',
    
    // 문의 생성/수정 에러
    INQUIRY_CREATE_FAILED: 'CUSTOMER_INVALID_INQUIRY_CREATE_FAILED',
    INQUIRY_UPDATE_FAILED: 'CUSTOMER_INVALID_INQUIRY_UPDATE_FAILED',
    INQUIRY_DELETE_FAILED: 'CUSTOMER_INVALID_INQUIRY_DELETE_FAILED',
    TICKET_CREATE_FAILED: 'CUSTOMER_INVALID_TICKET_CREATE_FAILED',
    TICKET_UPDATE_FAILED: 'CUSTOMER_INVALID_TICKET_UPDATE_FAILED',
    TICKET_CLOSE_FAILED: 'CUSTOMER_INVALID_TICKET_CLOSE_FAILED',
    
    // 답변 에러
    REPLY_CREATE_FAILED: 'CUSTOMER_INVALID_REPLY_CREATE_FAILED',
    REPLY_UPDATE_FAILED: 'CUSTOMER_INVALID_REPLY_UPDATE_FAILED',
    REPLY_DELETE_FAILED: 'CUSTOMER_INVALID_REPLY_DELETE_FAILED',
    
    // 상태 에러
    INQUIRY_ALREADY_CLOSED: 'CUSTOMER_CONFLICT_INQUIRY_ALREADY_CLOSED',
    TICKET_ALREADY_CLOSED: 'CUSTOMER_CONFLICT_TICKET_ALREADY_CLOSED',
    INQUIRY_ALREADY_ASSIGNED: 'CUSTOMER_CONFLICT_INQUIRY_ALREADY_ASSIGNED',
    TICKET_ALREADY_ASSIGNED: 'CUSTOMER_CONFLICT_TICKET_ALREADY_ASSIGNED',
  },

  // ===== 시스템 관련 에러 =====
  SYSTEM: {
    // 데이터베이스 에러
    DATABASE_CONNECTION_FAILED: 'SYSTEM_INTERNAL_DATABASE_CONNECTION_FAILED',
    DATABASE_QUERY_FAILED: 'SYSTEM_INTERNAL_DATABASE_QUERY_FAILED',
    DATABASE_TRANSACTION_FAILED: 'SYSTEM_INTERNAL_DATABASE_TRANSACTION_FAILED',
    DATABASE_CONSTRAINT_VIOLATION: 'SYSTEM_INTERNAL_DATABASE_CONSTRAINT_VIOLATION',
    
    // 캐시 에러
    CACHE_CONNECTION_FAILED: 'SYSTEM_INTERNAL_CACHE_CONNECTION_FAILED',
    CACHE_GET_FAILED: 'SYSTEM_INTERNAL_CACHE_GET_FAILED',
    CACHE_SET_FAILED: 'SYSTEM_INTERNAL_CACHE_SET_FAILED',
    CACHE_DELETE_FAILED: 'SYSTEM_INTERNAL_CACHE_DELETE_FAILED',
    
    // 외부 서비스 에러
    EXTERNAL_SERVICE_UNAVAILABLE: 'SYSTEM_INTERNAL_EXTERNAL_SERVICE_UNAVAILABLE',
    EXTERNAL_API_FAILED: 'SYSTEM_INTERNAL_EXTERNAL_API_FAILED',
    EXTERNAL_TIMEOUT: 'SYSTEM_INTERNAL_EXTERNAL_TIMEOUT',
    
    // 파일 시스템 에러
    FILE_UPLOAD_FAILED: 'SYSTEM_INTERNAL_FILE_UPLOAD_FAILED',
    FILE_DOWNLOAD_FAILED: 'SYSTEM_INTERNAL_FILE_DOWNLOAD_FAILED',
    FILE_DELETE_FAILED: 'SYSTEM_INTERNAL_FILE_DELETE_FAILED',
    FILE_NOT_FOUND: 'SYSTEM_NOT_FOUND_FILE_NOT_FOUND',
    
    // 설정 에러
    CONFIG_MISSING: 'SYSTEM_INTERNAL_CONFIG_MISSING',
    CONFIG_INVALID: 'SYSTEM_INTERNAL_CONFIG_INVALID',
    ENV_VARIABLE_MISSING: 'SYSTEM_INTERNAL_ENV_VARIABLE_MISSING',
    
    // 일반 시스템 에러
    INTERNAL_SERVER_ERROR: 'SYSTEM_INTERNAL_INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SYSTEM_MAINTENANCE_SERVICE_UNAVAILABLE',
    MAINTENANCE_MODE: 'SYSTEM_MAINTENANCE_MAINTENANCE_MODE',
  },

  // ===== 입력 검증 관련 에러 =====
  VALIDATION: {
    // 필수 필드 에러
    REQUIRED_FIELD_MISSING: 'VALIDATION_INVALID_REQUIRED_FIELD_MISSING',
    REQUIRED_EMAIL_MISSING: 'VALIDATION_INVALID_REQUIRED_EMAIL_MISSING',
    REQUIRED_PASSWORD_MISSING: 'VALIDATION_INVALID_REQUIRED_PASSWORD_MISSING',
    REQUIRED_USERNAME_MISSING: 'VALIDATION_INVALID_REQUIRED_USERNAME_MISSING',
    
    // 형식 에러
    INVALID_EMAIL_FORMAT: 'VALIDATION_INVALID_INVALID_EMAIL_FORMAT',
    INVALID_PASSWORD_FORMAT: 'VALIDATION_INVALID_INVALID_PASSWORD_FORMAT',
    INVALID_PHONE_FORMAT: 'VALIDATION_INVALID_INVALID_PHONE_FORMAT',
    INVALID_DATE_FORMAT: 'VALIDATION_INVALID_INVALID_DATE_FORMAT',
    INVALID_UUID_FORMAT: 'VALIDATION_INVALID_INVALID_UUID_FORMAT',
    INVALID_JSON_FORMAT: 'VALIDATION_INVALID_INVALID_JSON_FORMAT',
    
    // 길이 에러
    PASSWORD_TOO_SHORT: 'VALIDATION_INVALID_PASSWORD_TOO_SHORT',
    PASSWORD_TOO_LONG: 'VALIDATION_INVALID_PASSWORD_TOO_LONG',
    USERNAME_TOO_SHORT: 'VALIDATION_INVALID_USERNAME_TOO_SHORT',
    USERNAME_TOO_LONG: 'VALIDATION_INVALID_USERNAME_TOO_LONG',
    MESSAGE_TOO_LONG: 'VALIDATION_INVALID_MESSAGE_TOO_LONG',
    
    // 범위 에러
    VALUE_OUT_OF_RANGE: 'VALIDATION_INVALID_VALUE_OUT_OF_RANGE',
    AMOUNT_INVALID: 'VALIDATION_INVALID_AMOUNT_INVALID',
    PRICE_INVALID: 'VALIDATION_INVALID_PRICE_INVALID',
    QUANTITY_INVALID: 'VALIDATION_INVALID_QUANTITY_INVALID',
    
    // 타입 에러
    INVALID_DATA_TYPE: 'VALIDATION_INVALID_INVALID_DATA_TYPE',
    INVALID_ENUM_VALUE: 'VALIDATION_INVALID_INVALID_ENUM_VALUE',
    INVALID_BOOLEAN_VALUE: 'VALIDATION_INVALID_INVALID_BOOLEAN_VALUE',
    INVALID_NUMBER_VALUE: 'VALIDATION_INVALID_INVALID_NUMBER_VALUE',
  },

  // ===== 네트워크 관련 에러 =====
  NETWORK: {
    // 연결 에러
    CONNECTION_FAILED: 'NETWORK_INTERNAL_CONNECTION_FAILED',
    CONNECTION_TIMEOUT: 'NETWORK_INTERNAL_CONNECTION_TIMEOUT',
    CONNECTION_REFUSED: 'NETWORK_INTERNAL_CONNECTION_REFUSED',
    
    // 요청 에러
    REQUEST_FAILED: 'NETWORK_INTERNAL_REQUEST_FAILED',
    REQUEST_TIMEOUT: 'NETWORK_INTERNAL_REQUEST_TIMEOUT',
    REQUEST_ABORTED: 'NETWORK_INTERNAL_REQUEST_ABORTED',
    
    // 응답 에러
    RESPONSE_INVALID: 'NETWORK_INTERNAL_RESPONSE_INVALID',
    RESPONSE_TIMEOUT: 'NETWORK_INTERNAL_RESPONSE_TIMEOUT',
    RESPONSE_EMPTY: 'NETWORK_INTERNAL_RESPONSE_EMPTY',
    
    // DNS 에러
    DNS_RESOLUTION_FAILED: 'NETWORK_INTERNAL_DNS_RESOLUTION_FAILED',
    DNS_TIMEOUT: 'NETWORK_INTERNAL_DNS_TIMEOUT',
    
    // SSL/TLS 에러
    SSL_HANDSHAKE_FAILED: 'NETWORK_INTERNAL_SSL_HANDSHAKE_FAILED',
    CERTIFICATE_INVALID: 'NETWORK_INTERNAL_CERTIFICATE_INVALID',
    CERTIFICATE_EXPIRED: 'NETWORK_INTERNAL_CERTIFICATE_EXPIRED',
  },

  // ===== 요청 제한 관련 에러 =====
  RATE_LIMIT: {
    // 일반 제한
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_RATE_LIMIT_EXCEEDED',
    TOO_MANY_REQUESTS: 'RATE_LIMIT_RATE_LIMIT_TOO_MANY_REQUESTS',
    QUOTA_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_QUOTA_EXCEEDED',
    
    // 특정 액션 제한
    LOGIN_ATTEMPTS_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_LOGIN_ATTEMPTS_EXCEEDED',
    PASSWORD_RESET_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_PASSWORD_RESET_EXCEEDED',
    REGISTRATION_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_REGISTRATION_EXCEEDED',
    API_CALLS_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_API_CALLS_EXCEEDED',
    
    // 시간 기반 제한
    HOURLY_LIMIT_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_HOURLY_LIMIT_EXCEEDED',
    DAILY_LIMIT_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_DAILY_LIMIT_EXCEEDED',
    MONTHLY_LIMIT_EXCEEDED: 'RATE_LIMIT_RATE_LIMIT_MONTHLY_LIMIT_EXCEEDED',
  },
} as const;

// 도메인별 에러코드 타입
export type AuthErrorCode = typeof ERROR_CODES.AUTH[keyof typeof ERROR_CODES.AUTH];
export type UserErrorCode = typeof ERROR_CODES.USER[keyof typeof ERROR_CODES.USER];
export type PermissionErrorCode = typeof ERROR_CODES.PERMISSION[keyof typeof ERROR_CODES.PERMISSION];
export type WalletErrorCode = typeof ERROR_CODES.WALLET[keyof typeof ERROR_CODES.WALLET];
export type CustomerErrorCode = typeof ERROR_CODES.CUSTOMER[keyof typeof ERROR_CODES.CUSTOMER];
export type SystemErrorCode = typeof ERROR_CODES.SYSTEM[keyof typeof ERROR_CODES.SYSTEM];
export type ValidationErrorCode = typeof ERROR_CODES.VALIDATION[keyof typeof ERROR_CODES.VALIDATION];
export type NetworkErrorCode = typeof ERROR_CODES.NETWORK[keyof typeof ERROR_CODES.NETWORK];
export type RateLimitErrorCode = typeof ERROR_CODES.RATE_LIMIT[keyof typeof ERROR_CODES.RATE_LIMIT];

// 에러코드 타입 정의
export type ErrorCode = 
  | AuthErrorCode 
  | UserErrorCode 
  | PermissionErrorCode 
  | WalletErrorCode 
  | CustomerErrorCode 
  | SystemErrorCode 
  | ValidationErrorCode 
  | NetworkErrorCode 
  | RateLimitErrorCode;
